### ISSUE TITLE
Program hangs during convertToDemoIDs

### ISSUE THREAD

**Issue by Faterou** [ReagentX/HLTVDemoDownloader#3]
Hello! Thanks for the useful script.

Sometimes, the program hangs during convertToDemoIDs. More specifically on the line pool.map(getDemoIDs, match IDs). For example, when I try to download all the demos from the Krakow major (ID: 2720), I convert 38 or 39 demos and then it hangs. It is not always the same demos that can't be converted. It also does not only happen with Krakow, same thing happens with ESEA Premier Season 25 Europe (ID: 2879). It does not happen on some events, so it can't be a misuse by me.

I'm investigating this at the moment but it's hard work debugging multiple threads.

PS: I'm on Windows with Python 2.7.13.

**Comment by ReagentX** [comment]
Are you sure this is not related to your network? I've successfully downloaded both of the events you listed.

**Comment by ReagentX** [comment]
To clarify: my guess is that your problem lies with line 194:

`response = opener.open(url)`

Try adding a `print` before and after this line. I would be the first one prints but the second one does not. If that is the case, the problem is with your network not connecting fast enough to HLTV (or HLTV refusing your connection).

**Comment by Faterou** [comment]
It doesn't seem to be the problem. I get through both prints and I get 40 code 200 for the 40 matches.

**Comment by Faterou** [comment]
It works when I go through the getDemoIDs function line by line one thread at a time. So it seems like a problem with the map function when all the threads are executed at the same time...

**Comment by ReagentX** [comment]
Try reducing the number of threads on line 218 and see if that helps.

**Comment by Faterou** [comment]
I got it to work once with 32 threads. It works much more often with 16 but not all the time. Still haven't had a problem with 1 thread hahaha.

Also, I found that when I have some threads that hang, they all hang on `html = response.read()` on line 197.

I'll work with 1 thread, I don't mind it being longer. I suggest adding a script parameter or a prompt to set the number of threads (I can do a pull request if needed).

Thanks!

**Comment by ReagentX** [comment]
Line 197 just reads the HTTP request so if that line is failing then something weird is happening with line 194 related to your network connection.

**Comment by Faterou** [comment]
I used the [hanging_threads package](https://pypi.python.org/pypi/hanging_threads/2.0.3) to monitor my threads and I get this stacktrace indicating that the thread was stuck for 30 seconds: 

```
----------           Thread 5332 hangs            ----------
	File "****\Python27\lib\threading.py", line 774, in __bootstrap
		self.__bootstrap_inner()
	File "****\Python27\lib\threading.py", line 801, in __bootstrap_inner
		self.run()
	File "****\Python27\lib\threading.py", line 754, in run
		self.__target(*self.__args, **self.__kwargs)
	File "****\Python27\lib\multiprocessing\pool.py", line 113, in worker
		result = (True, func(*args, **kwds))
	File "****\Python27\lib\multiprocessing\pool.py", line 65, in mapstar
		return map(*args)
	File "****/HLTVDemoDownloader/Downloader.py", line 94, in getDemoIDs
		html = getHTML(url)
	File "****/HLTVDemoDownloader/Downloader.py", line 202, in getHTML
		html = response.read()
	File "****\Python27\lib\socket.py", line 355, in read
		data = self._sock.recv(rbufsize)
	File "****\Python27\lib\httplib.py", line 573, in read
		return self._read_chunked(amt)
	File "****\Python27\lib\httplib.py", line 615, in _read_chunked
		line = self.fp.readline(_MAXLINE + 1)
	File "****\Python27\lib\socket.py", line 480, in readline
		data = self._sock.recv(self._rbufsize)
	File "****\Python27\lib\ssl.py", line 766, in recv
		return self.read(buflen)
	File "****\Python27\lib\ssl.py", line 653, in read
		v = self._sslobj.read(len)
```

I guess this doesn't rule out the internet connection explanation. I just highly doubt it, no clue what could be wrong with my connection.

**Comment by ReagentX** [comment]
Looks like it hangs for you when validating SSL certificates. I am not able to replicate this on any of my machines.
